apiVersion: v1
kind: ReplicaSet
metadata: 
  name: myapp-pod
  labels: 
    app: myapp
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx

